SELECT first_name FROM customer
UNION ALL
SELECT first_name FROM actor
ORDER BY first_name
LIMIT 20;
--UNION JOINS TO TABLES AS LONG AS ITS THE SAME AMOUNT OF TABLES AND THE SAME
--DATA TYPE
--UNION POOLS TOGETHER ALL DATA INTO THE SAME DATA TYPES EXCLUDING ANY DUPLICATE INFO